### ISSUE TITLE
1D visualization doesn't work?

### ISSUE THREAD

**Issue by asinghvi17** [Ferrite-FEM/FerriteViz.jl#127]
It looks like FerriteViz always assumes triangles are available, meaning 1D visualizations won't work.  This isn't a problem for 2+ dimensional data because triangles are always available.

Is there any interest in fixing that?  I just tried to visualize a system created with `generate_grid(Line, (20,))` and immediately got an error:
```
ERROR: MethodError: no method matching ntriangles(::Line)

Closest candidates are:
  ntriangles(::Ferrite.AbstractCell{<:RefHexahedron})
   @ FerriteViz ~/.julia/dev/FerriteViz/src/utils.jl:194
  ntriangles(::Ferrite.AbstractCell{<:RefTetrahedron})
   @ FerriteViz ~/.julia/dev/FerriteViz/src/utils.jl:193
  ntriangles(::Ferrite.AbstractCell{<:RefQuadrilateral})
   @ FerriteViz ~/.julia/dev/FerriteViz/src/utils.jl:192
  ...

Stacktrace:
 [1] MakiePlotter(dh::DofHandler{1, Grid{1, Line, Float64}}, u::Vector{Float64}, topology::Nothing)
   @ FerriteViz ~/.julia/dev/FerriteViz/src/utils.jl:68
 [2] MakiePlotter(dh::DofHandler{1, Grid{1, Line, Float64}}, u::Vector{Float64})
   @ FerriteViz ~/.julia/dev/FerriteViz/src/utils.jl:97
 [3] top-level scope
   @ REPL[49]:1

```

**Comment by koehlerson** [comment]
related https://github.com/Ferrite-FEM/FerriteViz.jl/issues/41

I think the way to go is to add a field to the plotter that can hold line information https://github.com/Ferrite-FEM/FerriteViz.jl/issues/41#issuecomment-1801493625 

This would be of high interest, because I think there will be a lot of people that use structural elements such as trusses and beams that require 1D elements to be plotted (as well as Dennis' mentioned examples in the linked comment)

**Comment by asinghvi17** [comment]
Thanks for the reference!  Closing as duplicate then.
