### ISSUE TITLE
Cell data & higher order plotting

### ISSUE THREAD

**Issue by koehlerson** [Ferrite-FEM/FerriteViz.jl#8]
- [x] How do we plot stuff for cell dependent data instead of nodal data? Is it possible with Makie?
- [x] How to plot higher order stuff, possible in Makie?

**Comment by koehlerson** [comment]
regarding cell data: 

from Slack: We build sub-meshes using GeometryBasics.normal_mesh and then merge them into a single mesh object. It lets you plot discontinuous data. This is probably overkill for just cell centered data though.
https://github.com/trixi-framework/Trixi.jl/blob/4683894e8117cf6b5b8733f4e8c455ef7d972ce8/src/visualization/utilities.jl#L1201-L1226.

**Comment by termi-official** [comment]
Nodal discontinuous data is not possible, too. Bottleneck here is that the triangles are continuous along element boundaries.

**Comment by termi-official** [comment]
For geometry order > 1 it makes sense to hook into tesselation shaders (or at least tesselate via https://juliageometry.github.io/GeometryBasics.jl/stable/api/#GeometryBasics.Tesselation or smth)

**Comment by termi-official** [comment]
https://discourse.julialang.org/t/cuarray-glmakie/52461/9 might be a starter. We could use https://github.com/JuliaGPU/KernelAbstractions.jl for portable a tessellation kernel. Here two passes will be necessary.
1. Geometry tessellation
2. Solution tessellation

This is in general required because the solution can be highly nonlinear on geometrically linear regions vice versa.
